# Generated by Django 3.1.4 on 2020-12-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
                ('num_pags', models.SmallIntegerField()),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.autor')),
            ],
        ),
    ]
