# Generated by Django 3.1.4 on 2020-12-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor_id',
            new_name='autor',
        ),
    ]
